-- +goose Up
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Ensure enum exists (wrap DO in StatementBegin/End for goose)
-- +goose StatementBegin
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'role') THEN
    CREATE TYPE role AS ENUM ('user', 'admin');
  END IF;
END
$$;
-- +goose StatementEnd

CREATE TABLE IF NOT EXISTS persons (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id    UUID        NOT NULL DEFAULT gen_random_uuid(),
  email        TEXT        NOT NULL,
  username     TEXT        NOT NULL,
  password     TEXT        NOT NULL,
  role         role        NOT NULL DEFAULT 'user',
  is_active    BOOLEAN     NOT NULL DEFAULT FALSE,
  is_deleted   BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- +goose Down
DROP TABLE IF EXISTS persons;

-- +goose StatementBegin
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'role') THEN
    DROP TYPE role;
  END IF;
END
$$;
-- +goose StatementEnd
